global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: jenkins
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /prometheus
    scheme: http
    enable_http2: true
    static_configs:
      - targets: ['172.31.85.213:9100']
  - job_name: node_exporter
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    enable_http2: true
    static_configs:
      - targets: ['172.31.16.185:9100']
