apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: devops-monitoring
  labels:
    app.kubernetes.io/name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
    spec:
      securityContext:
        runAsUser: 1000  # Usuario 'ubuntu'
        runAsGroup: 1000 # Grupo 'ubuntu'
        fsGroup: 1000    # Asegura permisos de grupo para volúmenes
      containers:
      - name: prometheus
        image: prom/prometheus:v2.53.2 # Cambiar imagen a catálogo de RedHat si es necesario
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
        ports:
          - containerPort: 9090
        volumeMounts:
          - name: prometheus-storage
            mountPath: /prometheus
          - name: prometheus-config
            mountPath: /etc/prometheus
        securityContext:
          runAsUser: 1000  # Usuario 'ubuntu'
          runAsGroup: 1000  # Grupo 'ubuntu'
      volumes:
        - name: prometheus-storage
          emptyDir: {}  # Almacenamiento temporal que se elimina cuando el pod se destruye
        - name: prometheus-config
          configMap:
            name: prometheus-config
