apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: devops-monitoring
  labels:
    app.kubernetes.io/name: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      nodePort: 30001
  selector:
    app.kubernetes.io/name: prometheus